"use client";
import {useEffect,useMemo,useState} from "react";
const empty={facultyId:"",name:"",email:"",mobile:"",designation:"",qualification:"",joiningDate:"",departmentId:"",status:"ACTIVE"};
export default function FacultyPage(){const[rows,setRows]=useState([]),[deps,setDeps]=useState([]),[subs,setSubs]=useState([]),[form,setForm]=useState(empty),[edit,setEdit]=useState(null),[q,setQ]=useState(""),[cred,setCred]=useState(null),[err,setErr]=useState(""),[busy,setBusy]=useState(false);
async function load(){const r=await fetch("/api/admin/faculty");const d=await r.json();if(!r.ok)return setErr(d.error);setRows(d.faculty||[]);setDeps(d.departments||[]);setSubs(d.subjects||[])}useEffect(()=>{load()},[]);
const filtered=useMemo(()=>rows.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase())),[rows,q]);const set=(k,v)=>setForm(x=>({...x,[k]:v}));
async function save(e){e.preventDefault();setBusy(true);setErr("");try{const r=await fetch("/api/admin/faculty",{method:edit?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(edit?{id:edit,data:form}:{data:form})});const d=await r.json();if(!r.ok)throw Error(d.error);if(d.credentials)setCred(d.credentials);setForm(empty);setEdit(null);load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
async function remove(id){if(!confirm("Deactivate this faculty account?"))return;await fetch("/api/admin/faculty",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});load()}
async function assign(fid,sid){if(!sid)return;const r=await fetch("/api/admin/faculty",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"assignSubject",facultyId:fid,subjectId:sid})});const d=await r.json();if(!r.ok)setErr(d.error);load()}
async function unassign(fid,sid){await fetch("/api/admin/faculty",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"removeSubject",facultyId:fid,subjectId:sid})});load()}
return <main className="content" style={{padding:"32px",maxWidth:"1400px"}}><div className="eyebrow">NOBLE ERP • FACULTY MANAGEMENT</div><div style={{display:"flex",justifyContent:"flex-end",marginBottom:"12px"}}><button type="button" className="back" onClick={()=>{if(window.history.length>1)window.history.back();else window.location.href="/dashboard"}}>← Back to Dashboard</button></div><h1>Faculty Management</h1><p>Faculty accounts, department mapping and subject allocation.</p>{err&&<div className="error">{err}</div>}{cred&&<div className="panel" style={{margin:"18px 0"}}><b>Faculty account created.</b><p>Username: <strong>{cred.username}</strong> &nbsp; Password: <strong>{cred.password}</strong></p><small>Save it now; password is shown once.</small></div>}
<form onSubmit={save} style={{margin:"24px 0",padding:"22px",border:"1px solid #ddd",borderRadius:"18px",display:"grid",gap:"14px"}}><b>{edit?"Edit Faculty":"Add Faculty"}</b><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:"14px"}}>{[["facultyId","Faculty ID"],["name","Full Name"],["email","Email"],["mobile","Mobile"],["designation","Designation"],["qualification","Qualification"],["joiningDate","Joining Date"]].map(([k,l])=><label key={k}>{l}<input type={k==="email"?"email":k==="joiningDate"?"date":"text"} value={form[k]} onChange={e=>set(k,e.target.value)} required={k==="name"}/></label>)}<label>Department<select value={form.departmentId} onChange={e=>set("departmentId",e.target.value)}><option value="">Select</option>{deps.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>set("status",e.target.value)}><option>ACTIVE</option><option>INACTIVE</option></select></label></div><button className="primary" disabled={busy}>{busy?"Saving…":edit?"Update Faculty →":"Create Faculty + Account →"}</button></form>
<div className="panel"><div className="panelTitle"><b>Faculty ({filtered.length})</b><input placeholder="Search faculty…" value={q} onChange={e=>setQ(e.target.value)}/></div><div style={{overflowX:"auto"}}><table style={{width:"100%"}}><thead><tr>{["ID","Name","Department","Subjects","Status","Actions"].map(x=><th key={x} style={{textAlign:"left",padding:"10px"}}>{x}</th>)}</tr></thead><tbody>{filtered.map(f=><tr key={f.id}><td>{f.facultyId}</td><td>{f.name}</td><td>{f.department?.name||"—"}</td><td><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{f.subjects.map(s=><span key={s.subjectId} style={{padding:"4px 8px",border:"1px solid #ddd",borderRadius:10}}>{s.subject.code} <button type="button" onClick={()=>unassign(f.id,s.subjectId)}>×</button></span>)}<select onChange={e=>{assign(f.id,e.target.value);e.target.value=""}} defaultValue=""><option value="">+ Subject</option>{subs.filter(s=>!f.subjects.some(x=>x.subjectId===s.id)).map(s=><option key={s.id} value={s.id}>{s.code} — {s.name}</option>)}</select></div></td><td>{f.status}</td><td><button onClick={()=>{setEdit(f.id);setForm({facultyId:f.facultyId,name:f.name,email:f.email||"",mobile:f.mobile||"",designation:f.designation||"",qualification:f.qualification||"",joiningDate:f.joiningDate?f.joiningDate.slice(0,10):"",departmentId:f.departmentId||"",status:f.status});window.scrollTo({top:0,behavior:"smooth"})}}>Edit</button>{" "}<button onClick={()=>remove(f.id)}>Deactivate</button></td></tr>)}</tbody></table></div></div></main>}