"use client";

import ModuleHeader from "@/components/ModuleHeader";

import {useEffect,useMemo,useState} from "react";
export default function SubjectsPage(){
 const [subjects,setSubjects]=useState([]),[faculty,setFaculty]=useState([]),[deps,setDeps]=useState([]),[programs,setPrograms]=useState([]),[semesters,setSemesters]=useState([]),[form,setForm]=useState({code:"",name:"",credits:"",type:"THEORY",departmentId:"",programId:"",semesterId:""}),[edit,setEdit]=useState(null),[q,setQ]=useState(""),[busy,setBusy]=useState(false),[err,setErr]=useState("");
 async function load(){const [s,f,p,a]=await Promise.all([fetch("/api/admin/core?module=subjects"),fetch("/api/admin/faculty"),fetch("/api/admin/core?module=programs"),fetch("/api/admin/core?module=semesters")]);const sd=await s.json(),fd=await f.json(),pd=await p.json(),ad=await a.json();if(!s.ok||!f.ok||!p.ok||!a.ok){setErr("Unable to load academic data.");return}setSubjects(sd.rows||[]);setFaculty(fd.faculty||[]);setDeps(fd.departments||[]);setPrograms(pd.rows||[]);setSemesters(ad.rows||[])}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>subjects.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase())),[subjects,q]);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 async function save(e){e.preventDefault();setBusy(true);setErr("");try{const r=await fetch("/api/admin/core",{method:edit?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({module:"subjects",id:edit,data:form})});const d=await r.json();if(!r.ok)throw Error(d.error);setForm({code:"",name:"",credits:"",type:"THEORY",departmentId:"",programId:"",semesterId:""});setEdit(null);await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function assign(fid,sid){const r=await fetch("/api/admin/faculty",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"assignSubject",facultyId:fid,subjectId:sid})});const d=await r.json();if(!r.ok)setErr(d.error);else await load()}
 async function unassign(fid,sid){await fetch("/api/admin/faculty",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"removeSubject",facultyId:fid,subjectId:sid})});await load()}
 function label(arr,id){return arr.find(x=>x.id===id)?.name||"—"}
 return <main className="content" style={{padding:"32px",maxWidth:"1450px"}}><ModuleHeader eyebrow="NOBLE ERP • SUBJECT MANAGEMENT" title="Subject Management" description="Create subjects, map academic structure and manage faculty allocation." />{err&&<div className="error">{err}</div>}
 <form onSubmit={save} style={{margin:"24px 0",padding:22,border:"1px solid #ddd",borderRadius:18,display:"grid",gap:14}}><b>{edit?"Edit Subject":"Add Subject"}</b><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:14}}>
 <label>Code<input value={form.code} onChange={e=>set("code",e.target.value)} required/></label><label>Subject Name<input value={form.name} onChange={e=>set("name",e.target.value)} required/></label><label>Credits<input type="number" step="0.5" value={form.credits} onChange={e=>set("credits",e.target.value)}/></label><label>Type<select value={form.type} onChange={e=>set("type",e.target.value)}><option>THEORY</option><option>PRACTICAL</option><option>PROJECT</option><option>ELECTIVE</option></select></label>
 <label>Department<select value={form.departmentId} onChange={e=>set("departmentId",e.target.value)}><option value="">Select</option>{deps.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label><label>Program<select value={form.programId} onChange={e=>set("programId",e.target.value)}><option value="">Select</option>{programs.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label><label>Semester<select value={form.semesterId} onChange={e=>set("semesterId",e.target.value)}><option value="">Select</option>{semesters.map(x=><option key={x.id} value={x.id}>Sem {x.number} — {x.name}</option>)}</select></label></div><button className="primary" disabled={busy}>{busy?"Saving…":edit?"Update Subject →":"Create Subject →"}</button></form>
 <div className="panel"><div className="panelTitle"><b>Subjects ({filtered.length})</b><input placeholder="Search…" value={q} onChange={e=>setQ(e.target.value)}/></div><div style={{overflowX:"auto"}}><table style={{width:"100%"}}><thead><tr>{["Code","Subject","Department","Program","Semester","Credits","Faculty","Actions"].map(x=><th key={x} style={{textAlign:"left",padding:10}}>{x}</th>)}</tr></thead><tbody>{filtered.map(s=><tr key={s.id}><td>{s.code}</td><td>{s.name}</td><td>{label(deps,s.departmentId)}</td><td>{label(programs,s.programId)}</td><td>{(semesters.find(x=>x.id===s.semesterId)?.number)||"—"}</td><td>{s.credits??"—"}</td><td><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{faculty.filter(f=>f.subjects?.some(x=>x.subjectId===s.id)).map(f=><span key={f.id} style={{border:"1px solid #ddd",borderRadius:10,padding:"4px 8px"}}>{f.name} <button type="button" onClick={()=>unassign(f.id,s.id)}>×</button></span>)}<select defaultValue="" onChange={e=>{assign(e.target.value,s.id);e.target.value=""}}><option value="">+ Faculty</option>{faculty.filter(f=>!f.subjects?.some(x=>x.subjectId===s.id)&&(!s.departmentId||!f.departmentId||f.departmentId===s.departmentId)).map(f=><option key={f.id} value={f.id}>{f.facultyId} — {f.name}</option>)}</select></div></td><td><button onClick={()=>{setEdit(s.id);setForm({code:s.code,name:s.name,credits:s.credits??"",type:s.type||"THEORY",departmentId:s.departmentId||"",programId:s.programId||"",semesterId:s.semesterId||""});window.scrollTo({top:0,behavior:"smooth"})}}>Edit</button></td></tr>)}</tbody></table></div></div></main>
}