"use client";

import ModuleHeader from "@/components/ModuleHeader";
import AdminShell from "@/components/AdminShell";

import {useEffect,useState} from "react";
const date=d=>d?new Date(d).toISOString().slice(0,10):"";
export default function ExaminationPage(){
 const [d,setD]=useState({exams:[],years:[],subjects:[],rooms:[]}),[form,setForm]=useState({name:"",examType:"SEMESTER",academicYearId:"",startDate:"",endDate:"",status:"DRAFT"}),[sch,setSch]=useState({examId:"",subjectId:"",date:"",startTime:"",endTime:"",roomId:""}),[edit,setEdit]=useState(null),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/exams");const text=await r.text();let x={};try{x=text?JSON.parse(text):{}}catch{throw new Error("Server returned an invalid response.")}if(!r.ok)throw new Error(x.error||"Unable to load.");setD(x)}catch(e){setMsg(e.message||"Unable to load.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const set=(k,v)=>setForm(x=>({...x,[k]:v})); const ss=(k,v)=>setSch(x=>({...x,[k]:v}));
 async function save(e){e.preventDefault();try{const r=await fetch("/api/admin/exams",{method:edit?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,id:edit})});const text=await r.text();let x={};try{x=text?JSON.parse(text):{}}catch{throw new Error("Server returned an invalid response.")}if(!r.ok)throw new Error(x.error||"Save failed.");setMsg("Exam saved.");setForm({name:"",examType:"SEMESTER",academicYearId:"",startDate:"",endDate:"",status:"DRAFT"});setEdit(null);load()}catch(e){setMsg(e.message||"Save failed.")}}
 async function schedule(e){e.preventDefault();try{const r=await fetch("/api/admin/exams",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"schedule",...sch})});const text=await r.text();let x={};try{x=text?JSON.parse(text):{}}catch{throw new Error("Server returned an invalid response.")}if(!r.ok)throw new Error(x.error||"Schedule failed.");setMsg("Schedule saved.");setSch(x=>({...x,subjectId:"",date:"",startTime:"",endTime:"",roomId:""}));load()}catch(e){setMsg(e.message||"Schedule failed.")}}
 async function del(id){if(!confirm("Delete this exam?"))return;try{const r=await fetch("/api/admin/exams",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const text=await r.text();let x={};try{x=text?JSON.parse(text):{}}catch{throw new Error("Server returned an invalid response.")}if(!r.ok)throw new Error(x.error||"Delete failed.");setMsg("Exam deleted.");load()}catch(e){setMsg(e.message||"Delete failed.")}}
 async function delS(id){
   if(!confirm("Delete this subject schedule?"))return;
   try{
     const r=await fetch("/api/admin/exams",{method:"DELETE",headers:{"Content-Type":"application/json"},body: JSON.stringify({ scheduleId: id })});
     const text=await r.text();
     let x={}; try{x=text?JSON.parse(text):{}}catch{throw new Error("Server returned an invalid response.")}
     if(!r.ok)throw new Error(x.error||"Delete failed.");
     setMsg("Schedule deleted."); load();
   }catch(e){setMsg(e.message||"Delete failed.")}
 }
 return <AdminShell active="Examination"><main className="content" style={{padding:"32px",maxWidth:"1500px"}}><ModuleHeader eyebrow="NOBLE ERP • EXAMINATION" title="Examination Management" description="Create examinations, schedule subjects, allocate rooms and manage examination records." />{msg&&<div className="error">{msg}</div>}
 <form onSubmit={save} className="panel" style={{padding:22,margin:"22px 0"}}><div className="panelTitle"><b>{edit?"Edit Examination":"Create Examination"}</b></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}><label>Name<input required value={form.name} onChange={e=>set("name",e.target.value)}/></label><label>Type<select value={form.examType} onChange={e=>set("examType",e.target.value)}><option>SEMESTER</option><option>INTERNAL</option><option>UNIT TEST</option><option>PRACTICAL</option><option>BACKLOG</option></select></label><label>Academic Year<select value={form.academicYearId} onChange={e=>set("academicYearId",e.target.value)}><option value="">Select</option>{d.years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label><label>Start<input type="date" value={form.startDate} onChange={e=>set("startDate",e.target.value)}/></label><label>End<input type="date" value={form.endDate} onChange={e=>set("endDate",e.target.value)}/></label><label>Status<select value={form.status} onChange={e=>set("status",e.target.value)}><option>DRAFT</option><option>PUBLISHED</option><option>COMPLETED</option></select></label></div><button className="primary">{edit?"Update Exam":"Create Exam"} →</button></form>
 <form onSubmit={schedule} className="panel" style={{padding:22,margin:"22px 0"}}><div className="panelTitle"><b>Add / Update Subject Schedule</b></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}><label>Exam<select required value={sch.examId} onChange={e=>ss("examId",e.target.value)}><option value="">Select</option>{d.exams.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Subject<select required value={sch.subjectId} onChange={e=>ss("subjectId",e.target.value)}><option value="">Select</option>{d.subjects.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label><label>Date<input type="date" required value={sch.date} onChange={e=>ss("date",e.target.value)}/></label><label>Start<input type="time" required value={sch.startTime} onChange={e=>ss("startTime",e.target.value)}/></label><label>End<input type="time" required value={sch.endTime} onChange={e=>ss("endTime",e.target.value)}/></label><label>Room / Hall<select value={sch.roomId} onChange={e=>ss("roomId",e.target.value)}><option value="">Unassigned</option>{d.rooms.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label></div><button className="primary">Save Schedule →</button></form>
 <div className="panel" style={{padding:22}}><div className="panelTitle"><b>Examinations</b></div>{loading?<p>Loading…</p>:d.exams.map(x=><div key={x.id} style={{border:"1px solid #ddd",borderRadius:16,padding:16,marginBottom:14}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><b>{x.name}</b><div>{x.examType} • {x.academicYear?.name||"No academic year"} • {x.status}</div></div><div><button onClick={()=>{setEdit(x.id);setForm({name:x.name,examType:x.examType,academicYearId:x.academicYearId||"",startDate:date(x.startDate),endDate:date(x.endDate),status:x.status})}}>Edit</button> <button onClick={()=>del(x.id)}>Delete</button></div></div><div style={{overflowX:"auto",marginTop:12}}><table><thead><tr><th>Subject</th><th>Date</th><th>Time</th><th>Room</th><th></th></tr></thead><tbody>{x.schedules.map(s=><tr key={s.id}><td>{s.subject?.code} — {s.subject?.name}</td><td>{date(s.date)}</td><td>{s.startTime}–{s.endTime}</td><td>{s.room?.code||"—"}</td><td><button onClick={()=>delS(s.id)}>Delete</button></td></tr>)}</tbody></table></div></div>)}</div>
 </main></AdminShell>
}