"use client";

import ModuleHeader from "@/components/ModuleHeader";
import AdminShell from "@/components/AdminShell";

import {useEffect,useState} from "react";
async function responseError(r,fallback){const t=await r.text();if(!t)return fallback;try{const j=JSON.parse(t);return j.error||fallback}catch{return t.slice(0,240)||fallback}}
export default function AttendanceReports(){const[d,setD]=useState({rows:[],summary:{},divisions:[],subjects:[]}),[from,setFrom]=useState(new Date().toISOString().slice(0,10)),[to,setTo]=useState(new Date().toISOString().slice(0,10)),[semester,setSemester]=useState(""),[division,setDivision]=useState(""),[subject,setSubject]=useState(""),[loading,setLoading]=useState(false),[err,setErr]=useState("");
async function load(){setLoading(true);setErr("");const r=await fetch("/api/admin/attendance/reports?from="+from+"&to="+to+"&semesterId="+semester+"&divisionId="+division+"&subjectId="+subject);if(!r.ok){setLoading(false);return setErr(await responseError(r,"Unable to load report."))}const x=await r.json();setLoading(false);setD(x)}useEffect(()=>{load()},[]);
function csv(){const h=["Student ID","Name","Division","Total","Present","Absent","Late","Attendance %","Defaulter"],body=d.rows.map(x=>[x.studentId,x.name,x.division,x.total,x.present,x.absent,x.late,x.percentage,x.defaulter?"YES":"NO"]),out=[h,...body].map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(",")).join("\n"),url=URL.createObjectURL(new Blob([out],{type:"text/csv"})),a=document.createElement("a");a.href=url;a.download="attendance-report.csv";a.click();URL.revokeObjectURL(url)}
async function pdf(){setLoading(true);setErr("");try{const qs=new URLSearchParams({from,to,semesterId:semester,divisionId:division,subjectId:subject,format:"pdf"});const r=await fetch("/api/admin/attendance/reports?"+qs);if(!r.ok)throw Error(await responseError(r,"Unable to create PDF."));const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="attendance-report.pdf";a.click();URL.revokeObjectURL(url)}catch(e){setErr(e.message||"Unable to create PDF.")}finally{setLoading(false)}}
return <AdminShell active="Attendance"><main><ModuleHeader eyebrow="NOBLE ERP • REPORTS" title="Attendance Reports" description="Generate percentage, present/absent, late and defaulter reports from live ERP data." />{err&&<div className="error">{err}</div>}<div className="panel" style={{margin:"20px 0"}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:14}}><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Semester<select value={semester} onChange={e=>{setSemester(e.target.value);setDivision("");}}><option value="">All semesters</option>{[1,2,3,4,5,6].map(x=><option key={x} value={x}>Semester {x}</option>)}</select></label><label>Division<select value={division} onChange={e=>setDivision(e.target.value)}><option value="">All divisions</option>{d.divisions.map(x=><option key={x.id} value={x.id}>{x.program?.code} • Sem {x.semester?.number} • {x.name}</option>)}</select></label><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}><option value="">All subjects</option>{d.subjects.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label></div><div style={{display:"flex",gap:10,marginTop:16}}><button className="primary" onClick={load}>{loading?"Loading…":"Generate Report"}</button><button onClick={pdf} disabled={loading}>Download PDF</button><button onClick={csv}>Export CSV</button><button onClick={()=>window.print()}>Print</button></div></div><div className="statGrid"><div><small>STUDENTS</small><b>{d.summary.students||0}</b></div><div><small>MARKED</small><b>{d.summary.marked||0}</b></div><div><small>PRESENT</small><b>{d.summary.present||0}</b></div><div><small>DEFAULTERS &lt; 75%</small><b>{d.summary.defaulters||0}</b></div></div><div className="panel" style={{marginTop:20,overflowX:"auto"}}><div className="panelTitle"><b>Student Attendance</b><span>{d.from} → {d.to}</span></div><table style={{width:"100%"}}><thead><tr><th>Student</th><th>ID</th><th>Division</th><th>Total</th><th>P</th><th>A</th><th>L</th><th>%</th><th>Status</th></tr></thead><tbody>{d.rows.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.studentId}</td><td>{x.division}</td><td>{x.total}</td><td>{x.present}</td><td>{x.absent}</td><td>{x.late}</td><td><b>{x.percentage}%</b></td><td>{x.defaulter?"Defaulter":"Regular"}</td></tr>)}</tbody></table></div></main></AdminShell>}
