"use client";
import {useEffect,useMemo,useState} from "react";
const empty={dayOfWeek:"1",startTime:"09:00",endTime:"10:00",divisionId:"",subjectId:"",facultyId:"",roomId:""};
const days=["","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
export default function TimetablePage(){const[data,setData]=useState({rows:[],divisions:[],subjects:[],faculty:[],rooms:[]}),[form,setForm]=useState(empty),[q,setQ]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch("/api/admin/timetable");const d=await r.json();if(!r.ok)return setErr(d.error);setData(d)}
 useEffect(()=>{load()},[]);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));const filtered=useMemo(()=>data.rows.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase())),[data.rows,q]);
 async function save(e){e.preventDefault();setBusy(true);setErr("");try{const r=await fetch("/api/admin/timetable",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw Error(d.error);setForm(empty);await load()}catch(e){setErr(e.message)}finally{setBusy(false)}}
 async function del(id){if(!confirm("Delete this timetable entry?"))return;await fetch("/api/admin/timetable",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});load()}
 return <main className="content" style={{padding:32,maxWidth:1450}}><div className="eyebrow">NOBLE ERP • TIMETABLE MANAGEMENT</div><h1>Timetable Management</h1><p>Create conflict-free class schedules for divisions, faculty and rooms.</p>{err&&<div className="error">{err}</div>}
 <form onSubmit={save} style={{margin:"24px 0",padding:22,border:"1px solid #ddd",borderRadius:18,display:"grid",gap:14}}><b>Add Timetable Entry</b><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:14}}>
 <label>Day<select value={form.dayOfWeek} onChange={e=>set("dayOfWeek",e.target.value)}>{days.slice(1).map((x,i)=><option key={x} value={i+1}>{x}</option>)}</select></label><label>Start<input type="time" value={form.startTime} onChange={e=>set("startTime",e.target.value)} required/></label><label>End<input type="time" value={form.endTime} onChange={e=>set("endTime",e.target.value)} required/></label>
 <label>Division<select value={form.divisionId} onChange={e=>set("divisionId",e.target.value)} required><option value="">Select</option>{data.divisions.map(x=><option key={x.id} value={x.id}>{x.program?.code} • Sem {x.semester?.number} • {x.name}</option>)}</select></label>
 <label>Subject<select value={form.subjectId} onChange={e=>set("subjectId",e.target.value)} required><option value="">Select</option>{data.subjects.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label>
 <label>Faculty<select value={form.facultyId} onChange={e=>set("facultyId",e.target.value)} required><option value="">Select</option>{data.faculty.map(x=><option key={x.id} value={x.id}>{x.facultyId} — {x.name}</option>)}</select></label>
 <label>Room / Lab<select value={form.roomId} onChange={e=>set("roomId",e.target.value)}><option value="">No room</option>{data.rooms.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label></div><button className="primary" disabled={busy}>{busy?"Checking clashes…":"Add to Timetable →"}</button></form>
 <div className="panel"><div className="panelTitle"><b>Schedule ({filtered.length})</b><input placeholder="Search…" value={q} onChange={e=>setQ(e.target.value)}/></div><div style={{overflowX:"auto"}}><table style={{width:"100%"}}><thead><tr>{["Day","Time","Division","Subject","Faculty","Room","Action"].map(x=><th key={x} style={{textAlign:"left",padding:10}}>{x}</th>)}</tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td>{days[x.dayOfWeek]}</td><td>{x.startTime} – {x.endTime}</td><td>{x.division?.program?.code} / Sem {x.division?.semester?.number} / {x.division?.name}</td><td>{x.subject?.code} — {x.subject?.name}</td><td>{x.faculty?.name}</td><td>{x.room?.code||"—"}</td><td><button onClick={()=>del(x.id)}>Delete</button></td></tr>)}</tbody></table></div></div></main>}
